name: ${project.artifactId}
main: com.mcmiddleearth.mcme.events.Main
version: ${project.version}
authors: [DonoA, aaldim, lizzehface, meggawatts]
author: DonoA
depend: [WorldEdit]
commands:
    winter:
        description: Umbrella for all winter event commands
        usages: /winter <sub-command> [args]
